---
title: FedUpCoder
timezone: Europe/Belgrade
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
show_downloads: "false"
google_analytics: UA-105717460-1
theme: jekyll-theme-midnight
